export const mockData = [
  {
    cgid: 1,
    name: "John Doe",
    dialcode: "+1",
    mobile: "1234567890",
    email: "john.doe@example.com",
    status: "active",
  },
  {
    cgid: 2,
    name: "Jane Smith",
    dialcode: "+44",
    mobile: "9876543210",
    email: "jane.smith@example.com",
    status: "inactive",
  },
  {
    cgid: 3,
    name: "Alice Johnson",
    dialcode: "+61",
    mobile: "6549873210",
    email: "alice.johnson@example.com",
    status: "active",
  },
  {
    cgid: 4,
    name: "Bob Brown",
    dialcode: "+33",
    mobile: "7896541230",
    email: "bob.brown@example.com",
    status: "inactive",
  },
  {
    cgid: 5,
    name: "Emily Taylor",
    dialcode: "+49",
    mobile: "3214569870",
    email: "emily.taylor@example.com",
    status: "active",
  },
  {
    cgid: 6,
    name: "Michael Johnson",
    dialcode: "+61",
    mobile: "6543217890",
    email: "michael.johnson@example.com",
    status: "inactive",
  },
  {
    cgid: 7,
    name: "David Wilson",
    dialcode: "+44",
    mobile: "9873216540",
    email: "david.wilson@example.com",
    status: "active",
  },
  {
    cgid: 8,
    name: "Sarah Brown",
    dialcode: "+33",
    mobile: "1472583690",
    email: "sarah.brown@example.com",
    status: "active",
  },
  {
    cgid: 9,
    name: "Robert Garcia",
    dialcode: "+1",
    mobile: "3692581470",
    email: "robert.garcia@example.com",
    status: "inactive",
  },
  {
    cgid: 10,
    name: "Sophia Martinez",
    dialcode: "+49",
    mobile: "8529637410",
    email: "sophia.martinez@example.com",
    status: "active",
  },
  {
    cgid: 11,
    name: "Liam Johnson",
    dialcode: "+61",
    mobile: "1234567891",
    email: "liam.johnson@example.com",
    status: "active",
  },
  {
    cgid: 12,
    name: "Olivia Brown",
    dialcode: "+1",
    mobile: "9876543211",
    email: "olivia.brown@example.com",
    status: "inactive",
  },
  {
    cgid: 13,
    name: "William Garcia",
    dialcode: "+44",
    mobile: "6549873211",
    email: "william.garcia@example.com",
    status: "active",
  },
  {
    cgid: 14,
    name: "Emma Martinez",
    dialcode: "+49",
    mobile: "7896541231",
    email: "emma.martinez@example.com",
    status: "inactive",
  },
  {
    cgid: 15,
    name: "Noah Wilson",
    dialcode: "+33",
    mobile: "3214569871",
    email: "noah.wilson@example.com",
    status: "active",
  },
  {
    cgid: 16,
    name: "Ava Taylor",
    dialcode: "+1",
    mobile: "6543217891",
    email: "ava.taylor@example.com",
    status: "inactive",
  },
  {
    cgid: 17,
    name: "James Smith",
    dialcode: "+44",
    mobile: "9873216541",
    email: "james.smith@example.com",
    status: "active",
  },
  {
    cgid: 18,
    name: "Isabella Johnson",
    dialcode: "+61",
    mobile: "1472583691",
    email: "isabella.johnson@example.com",
    status: "active",
  },
  {
    cgid: 19,
    name: "Oliver Garcia",
    dialcode: "+33",
    mobile: "3692581471",
    email: "oliver.garcia@example.com",
    status: "inactive",
  },
  {
    cgid: 20,
    name: "Sophia Brown",
    dialcode: "+49",
    mobile: "8529637411",
    email: "sophia.brown@example.com",
    status: "active",
  },
  {
    cgid: 21,
    name: "Benjamin Martinez",
    dialcode: "+1",
    mobile: "1234567892",
    email: "benjamin.martinez@example.com",
    status: "active",
  },
  {
    cgid: 22,
    name: "Charlotte Wilson",
    dialcode: "+44",
    mobile: "9876543212",
    email: "charlotte.wilson@example.com",
    status: "inactive",
  },
  {
    cgid: 23,
    name: "Elijah Taylor",
    dialcode: "+61",
    mobile: "6549873212",
    email: "elijah.taylor@example.com",
    status: "active",
  },
  {
    cgid: 24,
    name: "Amelia Smith",
    dialcode: "+33",
    mobile: "7896541232",
    email: "amelia.smith@example.com",
    status: "inactive",
  },
  {
    cgid: 25,
    name: "Lucas Johnson",
    dialcode: "+49",
    mobile: "3214569872",
    email: "lucas.johnson@example.com",
    status: "active",
  },
  {
    cgid: 26,
    name: "Mia Garcia",
    dialcode: "+1",
    mobile: "6543217892",
    email: "mia.garcia@example.com",
    status: "inactive",
  },
  {
    cgid: 27,
    name: "Mason Wilson",
    dialcode: "+44",
    mobile: "9873216542",
    email: "mason.wilson@example.com",
    status: "active",
  },
  {
    cgid: 28,
    name: "Harper Brown",
    dialcode: "+61",
    mobile: "1472583692",
    email: "harper.brown@example.com",
    status: "active",
  },
  {
    cgid: 29,
    name: "Ethan Martinez",
    dialcode: "+33",
    mobile: "3692581472",
    email: "ethan.martinez@example.com",
    status: "inactive",
  },
  {
    cgid: 30,
    name: "Evelyn Taylor",
    dialcode: "+49",
    mobile: "8529637412",
    email: "evelyn.taylor@example.com",
    status: "active",
  },
  {
    cgid: 31,
    name: "Alexander Smith",
    dialcode: "+1",
    mobile: "1234567893",
    email: "alexander.smith@example.com",
    status: "active",
  },
  {
    cgid: 32,
    name: "Abigail Johnson",
    dialcode: "+44",
    mobile: "9876543213",
    email: "abigail.johnson@example.com",
    status: "inactive",
  },
  {
    cgid: 33,
    name: "Daniel Garcia",
    dialcode: "+61",
    mobile: "6549873213",
    email: "daniel.garcia@example.com",
    status: "active",
  },
  {
    cgid: 34,
    name: "Madison Martinez",
    dialcode: "+33",
    mobile: "7896541233",
    email: "madison.martinez@example.com",
    status: "inactive",
  },
  {
    cgid: 35,
    name: "Matthew Wilson",
    dialcode: "+49",
    mobile: "3214569873",
    email: "matthew.wilson@example.com",
    status: "active",
  },
  {
    cgid: 36,
    name: "Scarlett Brown",
    dialcode: "+1",
    mobile: "6543217893",
    email: "scarlett.brown@example.com",
    status: "inactive",
  },
  {
    cgid: 37,
    name: "Aiden Smith",
    dialcode: "+44",
    mobile: "9873216543",
    email: "aiden.smith@example.com",
    status: "active",
  },
  {
    cgid: 38,
    name: "Avery Johnson",
    dialcode: "+61",
    mobile: "1472583693",
    email: "avery.johnson@example.com",
    status: "active",
  },
  {
    cgid: 39,
    name: "Jackson Garcia",
    dialcode: "+33",
    mobile: "3692581473",
    email: "jackson.garcia@example.com",
    status: "inactive",
  },
  {
    cgid: 40,
    name: "Ella Martinez",
    dialcode: "+49",
    mobile: "8529637413",
    email: "ella.martinez@example.com",
    status: "active",
  },
  {
    cgid: 41,
    name: "Joseph Taylor",
    dialcode: "+1",
    mobile: "1234567894",
    email: "joseph.taylor@example.com",
    status: "active",
  },
  {
    cgid: 42,
    name: "Elizabeth Smith",
    dialcode: "+44",
    mobile: "9876543214",
    email: "elizabeth.smith@example.com",
    status: "inactive",
  },
  {
    cgid: 43,
    name: "Michael Johnson",
    dialcode: "+61",
    mobile: "6549873214",
    email: "michael.johnson@example.com",
    status: "active",
  },
  {
    cgid: 44,
    name: "Grace Martinez",
    dialcode: "+33",
    mobile: "7896541234",
    email: "grace.martinez@example.com",
    status: "inactive",
  },
  {
    cgid: 45,
    name: "Carter Wilson",
    dialcode: "+49",
    mobile: "3214569874",
    email: "carter.wilson@example.com",
    status: "active",
  },
  {
    cgid: 46,
    name: "Chloe Brown",
    dialcode: "+1",
    mobile: "6543217894",
    email: "chloe.brown@example.com",
    status: "inactive",
  },
  {
    cgid: 47,
    name: "Sebastian Smith",
    dialcode: "+44",
    mobile: "9873216544",
    email: "sebastian.smith@example.com",
    status: "active",
  },
  {
    cgid: 48,
    name: "Lily Johnson",
    dialcode: "+61",
    mobile: "1472583694",
    email: "lily.johnson@example.com",
    status: "active",
  },
  {
    cgid: 49,
    name: "Jack Garcia",
    dialcode: "+33",
    mobile: "3692581474",
    email: "jack.garcia@example.com",
    status: "inactive",
  },
  {
    cgid: 50,
    name: "Penelope Martinez",
    dialcode: "+49",
    mobile: "8529637414",
    email: "penelope.martinez@example.com",
    status: "active",
  },
  {
    cgid: 51,
    name: "Gabriel Taylor",
    dialcode: "+1",
    mobile: "1234567895",
    email: "gabriel.taylor@example.com",
    status: "active",
  },
];
